#!/usr/bin/env bash
# cg changelog: release notes rendered from real git history, matching what
# git-cliff produces from the repository's cliff.toml — a release per tag,
# groups from the commit-subject prefix, `[spec:<feature>/<task>]` turned into
# a task reference — with the snapshot renderer kept as the no-git fallback.
# The expectations below were checked against git-cliff 2.14.2 driven by a copy
# of cliff.toml pointed at github.com/acme/demo; the suite itself needs only git.
. "$(dirname "$0")/../lib.sh"

# before "<haystack>" "<first>" "<second>" — both present, in that order
before() {
    case "$1" in
        *"$2"*"$3"*) : ;;
        *) fail "expected '$2' before '$3' in output:
$(printf '%s\n' "$1" | head -20)" ;;
    esac
}

# count "<haystack>" "<needle>" — how many lines contain the needle
count() { printf '%s\n' "$1" | grep -c -- "$2" || true; }

cp -r "$FIXTURES/sample" "$TMP/proj"
cd "$TMP/proj"
"$CG" init >/dev/null

# ---- no git repository: the snapshot renderer still answers
"$CG" commit -m "first" >/dev/null
out="$("$CG" changelog)"
has "$out" "# Changelog"
has "$out" "Generated by Codify"
has "$out" "from local snapshots"

# ---- a scripted git history: one tagged release, one unreleased run
git init -q .
git config user.email "t@example.com"
git config user.name "Test"
git remote add origin https://github.com/acme/demo.git

git commit --allow-empty -q -m "feat: add gauge"
gauge="$(git rev-parse HEAD)"
git commit --allow-empty -q -m "fix(parser): handle empty input [spec:demo/1.2]"
parser="$(git rev-parse HEAD)"
git commit --allow-empty -q -m "guard: fewer false unknowns"
git commit --allow-empty -q -m "Plain subject without prefix"
git commit --allow-empty -q -m "Merge branch 'x' into main"
git tag 0.1.0
git commit --allow-empty -q -m "docs: explain gauges"
git commit --allow-empty -q -m "docs: explain gauges"
git commit --allow-empty -q -m "feat!: drop the old flag"

tagged="$(TZ=UTC git log -1 --date=format-local:%Y-%m-%d --format=%cd 0.1.0)"
today="$(date -u +%Y-%m-%d)"

out="$("$CG" changelog)"

# the header cliff.toml declares, not the snapshot one
has "$out" "# Changelog"
has "$out" "All notable changes to this project are recorded here, generated from git history."
hasnt "$out" "Generated by Codify"

# a release per tag; what follows the last tag is [Unreleased], listed first
before "$out" "## [Unreleased]" "## [0.1.0] - $tagged"

# groups come from the subject prefix, links from `git remote get-url origin`
has "$out" "### Features"
has "$out" "- Add gauge ([${gauge:0:7}](https://github.com/acme/demo/commit/$gauge))"

# `type(scope):` renders the scope in bold; a trailing [spec:...] a task ref
has "$out" "### Bug fixes"
has "$out" "- **parser:** Handle empty input ("
has "$out" "](https://github.com/acme/demo/commit/$parser), task demo/1.2)"

# a Codify area prefix is its own group
has "$out" "### Guard"
has "$out" "Fewer false unknowns"

# merge commits are not release notes
hasnt "$out" "Merge branch"

# a subject with no prefix lands in Other, first letter uppercased
before "$out" "### Other" "Plain subject without prefix"

# identical messages inside a group are listed once
has "$out" "### Documentation"
n="$(count "$out" "Explain gauges")"
[ "$n" -eq 1 ] || fail "expected one 'Explain gauges' bullet, got $n"

# `type!:` is marked breaking
has "$out" "[**breaking**] Drop the old flag"

# footer links: a compare range for Unreleased, a tag link for the release
has "$out" "[Unreleased]: https://github.com/acme/demo/compare/0.1.0...HEAD"
has "$out" "[0.1.0]: https://github.com/acme/demo/releases/tag/0.1.0"

# ---- --unreleased: only the pending section, with only its footer line
out="$("$CG" changelog --unreleased)"
has "$out" "## [Unreleased]"
has "$out" "Drop the old flag"
hasnt "$out" "## [0.1.0]"
has "$out" "[Unreleased]: https://github.com/acme/demo/compare/0.1.0...HEAD"
hasnt "$out" "[0.1.0]: https://github.com/acme/demo/releases/tag/0.1.0"

# ---- --tag names the pending section as a release dated today (UTC)
out="$("$CG" changelog --tag 0.2.0)"
has "$out" "## [0.2.0] - $today"
has "$out" "Drop the old flag"
hasnt "$out" "## [Unreleased]"

# ---- -n caps the release sections, Unreleased included
out="$("$CG" changelog -n 1)"
has "$out" "## [Unreleased]"
hasnt "$out" "## [0.1.0]"

# ---- -o writes the file relative to the repository root
out="$("$CG" changelog -o notes.md)"
has "$out" "wrote"
has "$out" "notes.md"
[ -f notes.md ] || fail "cg changelog -o did not create notes.md"
file="$(cat notes.md)"
has "$file" "# Changelog"
has "$file" "## [Unreleased]"
has "$file" "## [0.1.0] - $tagged"

# ---- --snapshots keeps the old renderer available inside a git repository
out="$("$CG" changelog --snapshots)"
has "$out" "Generated by Codify"
has "$out" "from local snapshots"
hasnt "$out" "## [Unreleased]"

echo "29_changelog ok"
