#!/usr/bin/env bash
# cg changelog: release notes rendered from real git history, matching what
# git-cliff produces from the repository's cliff.toml — a release per tag,
# groups from the commit-subject prefix, `[spec:<feature>/<task>]` turned into
# a task reference — with the snapshot renderer kept as the no-git fallback.
# The expectations below were checked against git-cliff 2.14.2 driven by a copy
# of cliff.toml pointed at github.com/acme/demo; the suite itself needs only git.
. "$(dirname "$0")/../lib.sh"

# before "<haystack>" "<first>" "<second>" — both present, in that order
before() {
    case "$1" in
        *"$2"*"$3"*) : ;;
        *) fail "expected '$2' before '$3' in output:
$(printf '%s\n' "$1" | head -20)" ;;
    esac
}

# count "<haystack>" "<needle>" — how many lines contain the needle
count() { printf '%s\n' "$1" | grep -c -- "$2" || true; }

cp -r "$FIXTURES/sample" "$TMP/proj"
cd "$TMP/proj"
"$CG" init >/dev/null

# ---- no git repository: the snapshot renderer still answers
"$CG" commit -m "first" >/dev/null
out="$("$CG" changelog)"
has "$out" "# Changelog"
has "$out" "Generated by Codify"
has "$out" "from local snapshots"

# ---- a scripted git history: one tagged release, one unreleased run.
#      The sample's package.json would name the head section by its version;
#      this scenario is about tags alone, so it goes.
rm -f package.json
git init -q .
git config user.email "t@example.com"
git config user.name "Test"
git remote add origin https://github.com/acme/demo.git

git commit --allow-empty -q -m "feat: add gauge"
gauge="$(git rev-parse HEAD)"
git commit --allow-empty -q -m "fix(parser): handle empty input [spec:demo/1.2]"
parser="$(git rev-parse HEAD)"
git commit --allow-empty -q -m "guard: fewer false unknowns"
git commit --allow-empty -q -m "Plain subject without prefix"
git commit --allow-empty -q -m "Merge branch 'x' into main"
git tag 0.1.0
git commit --allow-empty -q -m "docs: explain gauges"
git commit --allow-empty -q -m "docs: explain gauges"
git commit --allow-empty -q -m "feat!: drop the old flag"

tagged="$(TZ=UTC git log -1 --date=format-local:%Y-%m-%d --format=%cd 0.1.0)"
today="$(date -u +%Y-%m-%d)"

out="$("$CG" changelog)"

# the header cliff.toml declares, not the snapshot one
has "$out" "# Changelog"
has "$out" "All notable changes to this project are recorded here, generated from git history."
hasnt "$out" "Generated by Codify"

# a release per tag; what follows the last tag is [Unreleased], listed first
before "$out" "## [Unreleased]" "## [0.1.0] - $tagged"

# groups come from the subject prefix, links from `git remote get-url origin`
has "$out" "### Features"
has "$out" "- Add gauge ([${gauge:0:7}](https://github.com/acme/demo/commit/$gauge))"

# `type(scope):` renders the scope in bold; a trailing [spec:...] a task ref
has "$out" "### Bug fixes"
has "$out" "- **parser:** Handle empty input ("
has "$out" "](https://github.com/acme/demo/commit/$parser), task demo/1.2)"

# a Codify area prefix is its own group
has "$out" "### Guard"
has "$out" "Fewer false unknowns"

# merge commits are not release notes
hasnt "$out" "Merge branch"

# a subject with no prefix lands in Other, first letter uppercased
before "$out" "### Other" "Plain subject without prefix"

# identical messages inside a group are listed once
has "$out" "### Documentation"
n="$(count "$out" "Explain gauges")"
[ "$n" -eq 1 ] || fail "expected one 'Explain gauges' bullet, got $n"

# `type!:` is marked breaking
has "$out" "[**breaking**] Drop the old flag"

# footer links: a compare range for Unreleased, a tag link for the release
has "$out" "[Unreleased]: https://github.com/acme/demo/compare/0.1.0...HEAD"
has "$out" "[0.1.0]: https://github.com/acme/demo/releases/tag/0.1.0"

# ---- --unreleased: only the pending section, with only its footer line
out="$("$CG" changelog --unreleased)"
has "$out" "## [Unreleased]"
has "$out" "Drop the old flag"
hasnt "$out" "## [0.1.0]"
has "$out" "[Unreleased]: https://github.com/acme/demo/compare/0.1.0...HEAD"
hasnt "$out" "[0.1.0]: https://github.com/acme/demo/releases/tag/0.1.0"

# ---- --tag names the pending section as a release dated today (UTC)
out="$("$CG" changelog --tag 0.2.0)"
has "$out" "## [0.2.0] - $today"
has "$out" "Drop the old flag"
hasnt "$out" "## [Unreleased]"

# ---- -n caps the release sections, Unreleased included
out="$("$CG" changelog -n 1)"
has "$out" "## [Unreleased]"
hasnt "$out" "## [0.1.0]"

# ---- -o writes the file relative to the repository root
out="$("$CG" changelog -o notes.md)"
has "$out" "wrote"
has "$out" "notes.md"
[ -f notes.md ] || fail "cg changelog -o did not create notes.md"
file="$(cat notes.md)"
has "$file" "# Changelog"
has "$file" "## [Unreleased]"
has "$file" "## [0.1.0] - $tagged"

# ---- --snapshots keeps the old renderer available inside a git repository
out="$("$CG" changelog --snapshots)"
has "$out" "Generated by Codify"
has "$out" "from local snapshots"
hasnt "$out" "## [Unreleased]"

echo "29_changelog ok"

# ---- highlights: with a key, a model writes a Highlights block per release
#      from exactly the notes; without one nothing is called; a summary is
#      cached by its release's commits, so a rerun costs nothing new
export OPENAI_FAKE_DIR="$TMP/openai"
export CG_CHANGELOG_CURL="$FIXTURES/jev/fake-openai.sh"
out="$("$CG" changelog)"                              # no key: no call
hasnt "$out" "### Highlights"
[ ! -d "$OPENAI_FAKE_DIR" ] || fail "the model was called without a key"
rc=0; "$CG" changelog --summarize >/dev/null 2>"$TMP/err" || rc=$?
has "$(cat "$TMP/err")" "--summarize needs CENTRA_API_KEY"

# the key from the project's .env, even with a space in its name
printf 'CENTRA_API _KEY=sk-test-123\n' > .env
out="$("$CG" changelog)"
has "$out" "## [Unreleased]"
before "$out" "## [Unreleased]" "### Highlights"
before "$out" "### Highlights" "This release adds the gauge and hardens the parser"
before "$out" "hardens the parser" "### Documentation"    # prose first, then the record
has "$out" "- Gauges land in the UI"
n="$(ls "$OPENAI_FAKE_DIR"/req-*.json | wc -l)"
[ "$n" -eq 2 ] || fail "expected one call per release (2), got $n"
python3 - "$OPENAI_FAKE_DIR/req-1.json" "$OPENAI_FAKE_DIR/cfg-1.txt" <<'EOF2' || fail "request shape"
import json, sys
d = json.load(open(sys.argv[1]))
assert d["model"].startswith("openrouter/ling-3.0-flash-sante:free"), d["model"]
c = d["messages"][0]["content"]
assert "Drop the old flag" in c and "BREAKING" in c and "Explain gauges" in c, c
assert "Documentation:" in c and "Features:" in c, c
assert "do not invent" in c
cfg = open(sys.argv[2]).read()
assert "https://gateway.centra.ag/v1/chat/completions" in cfg, cfg
assert "Bearer sk-test-123" in cfg, cfg
EOF2
# the record itself is unchanged by the prose
has "$out" "- [**breaking**] Drop the old flag"
has "$out" "[Unreleased]: https://github.com/acme/demo/compare/0.1.0...HEAD"
# a rerun answers from the cache
"$CG" changelog >/dev/null
[ "$(ls "$OPENAI_FAKE_DIR"/req-*.json | wc -l)" -eq 2 ] || fail "a rerun called the model again"
# a new commit means one new call, for Unreleased only
git commit --trailer "Co-authored-by: Cursor <cursoragent@cursor.com>" --allow-empty -q -m "feat: add dials"
"$CG" changelog >/dev/null
[ "$(ls "$OPENAI_FAKE_DIR"/req-*.json | wc -l)" -eq 3 ] || fail "expected exactly one new call"
has "$(cat "$OPENAI_FAKE_DIR/req-3.json")" "Add dials"
# --no-summarize keeps the model out; a failing endpoint keeps the notes
out="$("$CG" changelog --no-summarize)"
hasnt "$out" "### Highlights"
: > "$OPENAI_FAKE_DIR/fail"
git commit --trailer "Co-authored-by: Cursor <cursoragent@cursor.com>" --allow-empty -q -m "feat: add knobs"
out="$("$CG" changelog 2>"$TMP/err")"
has "$out" "Add knobs"
has "$(cat "$TMP/err")" "highlights for Unreleased skipped"
has "$out" "### Highlights"                            # the cached 0.1.0 one stays
# the model, endpoint, and key can be pointed anywhere
rm -f "$OPENAI_FAKE_DIR/fail"
CG_CHANGELOG_MODEL=other/model CG_CHANGELOG_ENDPOINT=https://example.test/v1/chat/completions \
    CENTRA_API_KEY=sk-env "$CG" changelog --unreleased >/dev/null
last="$(ls "$OPENAI_FAKE_DIR"/req-*.json | sort -V | tail -1)"
has "$(cat "$last")" '"model":"other/model"'
lastcfg="$(ls "$OPENAI_FAKE_DIR"/cfg-*.txt | sort -V | tail -1)"
has "$(cat "$lastcfg")" "example.test"
has "$(cat "$lastcfg")" "Bearer sk-env"
# -o reports what it did
out="$("$CG" changelog -o notes.md)"
has "$out" "highlights by openrouter/ling-3.0-flash-sante:free"
has "$out" "from the cache"
# a reply that repeats the heading is not printed with it twice
: > "$OPENAI_FAKE_DIR/heading"
git commit --allow-empty -q -m "feat: add levers"
out="$("$CG" changelog --unreleased)"
rm -f "$OPENAI_FAKE_DIR/heading"
before "$out" "### Highlights" "Knobs and dials arrive."
[ "$(printf '%s\n' "$out" | grep -ci 'highlights')" -eq 1 ] || fail "the heading was repeated:
$out"

# ---- releases without tags: the version file's bumps are the boundaries,
#      and the head section is the version the tree carries, not Unreleased
rm -rf "$TMP/vr"; mkdir -p "$TMP/vr"; cd "$TMP/vr"
git init -q . && git config user.email t@t && git config user.name t
git remote add origin git@github.com:acme/vr.git
echo 0.1.0 > VERSION; git add -A; git commit -q -m "feat: first"
git commit --allow-empty -q -m "fix: early bug"
echo 0.2.0 > VERSION; git add -A; git commit -q -m "release: 0.2.0"
git commit --allow-empty -q -m "feat: second"
echo 0.3.0 > VERSION                                  # the release being prepared
"$CG" init >/dev/null
out="$("$CG" changelog --no-summarize)"
hasnt "$out" "Unreleased"
before "$out" "## [0.3.0] - $today" "## [0.2.0] - "
before "$out" "## [0.2.0] - " "## [0.1.0] - "
before "$out" "## [0.3.0]" "Second"                   # after the 0.2.0 bump
before "$out" "## [0.2.0]" "Early bug"                # up to and including the bump
before "$out" "## [0.2.0]" "### Releases"
before "$out" "## [0.1.0]" "First"
has "$out" "[0.3.0]: https://github.com/acme/vr/compare/0.2.0...0.3.0"
has "$out" "[0.2.0]: https://github.com/acme/vr/compare/0.1.0...0.2.0"
has "$out" "[0.1.0]: https://github.com/acme/vr/releases/tag/0.1.0"
# committed at the last version: nothing new, no empty section
git checkout -q -- VERSION
out="$("$CG" changelog --no-summarize)"
hasnt "$out" "0.3.0"
has "$out" "## [0.2.0]"
# no remote: bare hashes, no links, no footer
git remote remove origin
out="$("$CG" changelog --no-summarize)"
second="$(git log --format=%h -n1 --grep='feat: second' | cut -c1-7)"
has "$out" "- Second ($second)"
hasnt "$out" "](/commit/"
hasnt "$out" "[0.2.0]: "

echo "29_changelog highlights ok"
