#!/usr/bin/env bash
# cg codemap: CODEMAP.md from the graph — sections in order, byte-stable,
# budget-fitted with omission counts, marker-owned, --check, -o, --json,
# the MCP tool, and the brief line
. "$(dirname "$0")/../lib.sh"

cp -r "$FIXTURES/codemap" "$TMP/proj"
cp -r "$FIXTURES/specrepo/spec" "$TMP/proj/spec"
cd "$TMP/proj"
"$CG" init >/dev/null

# --- ac_1/ac_2: written at the root, sections in order, content grounded ---
"$CG" codemap >/dev/null
[ -s CODEMAP.md ] || fail "codemap did not write CODEMAP.md"
map="$(cat CODEMAP.md)"
head -1 CODEMAP.md | grep -q '^<!-- codify-owned: codemap v1 .*GENERATED by `cg codemap`' \
    || fail "first line is not the generated marker"
order="$(grep -n '^## ' CODEMAP.md | cut -d: -f2-)"
want='## Overview
## Layout
## Entry points
## Modules
## Dependencies
## Tests
## Workflow and agent files'
[ "$order" = "$want" ] || fail "sections out of order:
$order"
has "$map" "# Tally — code map"
has "$map" "> Tally counts words in text files."       # README prose
has "$map" "| c | 5 |"                                  # language counts
has "$map" '`make test`'                                # detected build/test
has "$map" '`src/` — 4 files'                           # layout
has "$map" '`main` — `src/main.c:6`'                    # entry point
has "$map" '`count`, `lines`, `help`'                   # dispatched commands
has "$map" "Text helpers: load a whole file"            # file's own comment
has "$map" '`text_words` function — `src/text.c:17`'    # ranked symbol
has "$map" 'int text_words(const char *s)'              # its signature
has "$map" '`tests/` → `src/`'                          # dependency edge
has "$map" '`test_count.c` — Unit tests for the word counter.'
has "$map" '`smoke.sh` — smoke test'                    # script purpose
has "$map" '`spec/workflow.kvx`'                        # workflow pointer
has "$map" '`spec/demo/spec.kvx` — the active feature'
has "$map" '`AGENTS.md`'
has "$map" '`docs/design.md` — Tally design notes'
hasnt "$map" "$TMP"                                     # no absolute paths
hasnt "$map" "TALLY_H"                                  # include guards
# no purpose is invented: docs/ has no README and no index file
grep -q '^- `docs/` — 1 file$' CODEMAP.md || fail "docs/ got an invented purpose"

# --- ac_3: byte-identical, and the map never counts itself ---
cp CODEMAP.md "$TMP/first.md"
out="$("$CG" codemap)"
has "$out" "unchanged"
cmp CODEMAP.md "$TMP/first.md" || fail "second run changed the bytes"
"$CG" sync >/dev/null
"$CG" codemap >/dev/null
cmp CODEMAP.md "$TMP/first.md" || fail "indexing CODEMAP.md changed the map"
hasnt "$(cat CODEMAP.md)" '`CODEMAP.md`'
expect_rc 0 "$CG" codemap --check

# --- ac_1: -o elsewhere, -o -, --json ---
mkdir -p out
"$CG" codemap -o out/MAP.md >/dev/null
[ -s out/MAP.md ] || fail "-o did not write"
cmp CODEMAP.md out/MAP.md || fail "-o map differs from the default map"
"$CG" codemap -o out/MAP.md >/dev/null
cmp CODEMAP.md out/MAP.md || fail "-o map counted itself on the rerun"
rm -rf out
"$CG" sync >/dev/null
stdout="$("$CG" codemap -o -)"
[ "$stdout" = "$(cat CODEMAP.md)" ] || fail "-o - differs from CODEMAP.md"
"$CG" codemap --json > "$TMP/map.json"
python3 - "$TMP/map.json" <<'EOF'
import json, sys
d = json.load(open(sys.argv[1]))
keys = list(d)
assert keys == ["format", "version", "name", "description", "budget",
                "tokens", "overview", "layout", "entry_points", "modules",
                "dependencies", "tests", "workflow"], keys
assert d["format"] == "codemap" and d["name"] == "Tally", d
assert d["overview"]["languages"][0] == {"name": "c", "files": 5, "lines": 78}
assert any("make test" in b["commands"] for b in d["overview"]["build"])
assert d["entry_points"]["commands"]["names"] == ["count", "lines", "help"]
src = [m for m in d["modules"]["items"] if m["path"] == "src"][0]
assert src["symbols"][0]["name"] == "text_words", src["symbols"][0]
assert src["symbols"][0]["signature"] == "int text_words(const char *s)"
assert d["dependencies"]["edges"][0]["from"] == "tests"
for sec in ("overview", "layout", "entry_points", "modules", "dependencies",
            "tests", "workflow"):
    assert "omitted" in d[sec], sec
EOF
"$CG" codemap --json > "$TMP/map2.json"
cmp "$TMP/map.json" "$TMP/map2.json" || fail "--json is not byte-stable"
expect_rc 2 "$CG" codemap --json -o x.json
expect_rc 2 "$CG" codemap --check -o -
expect_rc 2 "$CG" codemap --budget 0
expect_rc 2 "$CG" codemap --budget 10

# --- ac_4: the budget fits, least-referenced goes first, omissions counted ---
small="$("$CG" codemap -o - --budget 450)"
bytes=$(printf '%s\n' "$small" | wc -c)
[ "$bytes" -le 1800 ] || fail "budget 450 tokens gave $bytes bytes"
has "$small" "## Overview"
has "$small" "## Workflow and agent files"
has "$small" "_Not shown:"
# the most-called symbol outlives the least-called ones
if printf '%s' "$small" | grep -q '`count_lines`'; then
    has "$small" '`text_words`'
fi
"$CG" codemap --budget 450 >/dev/null
head -1 CODEMAP.md | grep -q 'budget=450' || fail "marker does not record the budget"
expect_rc 0 "$CG" codemap --check            # checks at the recorded budget
"$CG" codemap >/dev/null
cmp CODEMAP.md "$TMP/first.md" || fail "default budget did not restore the map"

# a larger tree: the sample fixture, squeezed
cp -r "$FIXTURES/sample" "$TMP/sample"
( cd "$TMP/sample" && "$CG" init >/dev/null
  full="$("$CG" codemap -o -)"
  has "$full" "# sample — code map"                  # package.json name
  has "$full" '`npm test`'
  has "$full" "Task persistence for the sample fixture."
  has "$full" '`GET /users'                          # routes
  tight="$("$CG" codemap -o - --budget 500)"
  b=$(printf '%s\n' "$tight" | wc -c)
  [ "$b" -le 2000 ] || fail "sample at 500 tokens: $b bytes"
  has "$tight" "_Not shown:"
  expect_rc 2 "$CG" codemap -o - --budget 300 )

# --- ac_5: the marker owns the file; --check and --force ---
printf '# Hand-written map\n' > CODEMAP.md
expect_rc 1 "$CG" codemap
[ "$(cat CODEMAP.md)" = "# Hand-written map" ] || fail "overwrote a hand-written map"
expect_rc 1 "$CG" codemap --check
"$CG" codemap --force >/dev/null
cmp CODEMAP.md "$TMP/first.md" || fail "--force did not regenerate"
expect_rc 0 "$CG" codemap --check
printf 'edited\n' >> CODEMAP.md
expect_rc 1 "$CG" codemap --check
"$CG" codemap >/dev/null                     # marker intact: no --force needed
expect_rc 0 "$CG" codemap --check
mv CODEMAP.md "$TMP/held.md"
out="$("$CG" codemap --check || true)"
has "$out" "missing"
expect_rc 1 "$CG" codemap --check
[ ! -e CODEMAP.md ] || fail "--check wrote a file"
mv "$TMP/held.md" CODEMAP.md

# --- ac_6: brief names the map and says whether it is stale ---
out="$("$CG" brief)"
has "$out" "codemap: CODEMAP.md (current)"
"$CG" brief --json > "$TMP/brief.json"
python3 - "$TMP/brief.json" <<'EOF'
import json, sys
d = json.load(open(sys.argv[1]))
assert d["codemap"] == {"path": "CODEMAP.md", "generated": True,
                        "stale": False}, d.get("codemap")
EOF
cat >> src/text.c <<'EOF'

int text_chars(const char *s) { int n = 0; while (s[n]) n++; return n; }
EOF
"$CG" sync >/dev/null
out="$("$CG" brief)"
has "$out" "codemap: CODEMAP.md (stale — run cg codemap)"
expect_rc 1 "$CG" codemap --check
"$CG" codemap >/dev/null
has "$("$CG" brief)" "codemap: CODEMAP.md (current)"
printf '# mine\n' > CODEMAP.md
has "$("$CG" brief)" "codemap: CODEMAP.md (not generated by cg codemap)"
rm CODEMAP.md
hasnt "$("$CG" brief)" "codemap:"

# --- ac_6: the MCP tool returns the map text and writes nothing ---
printf '%s\n%s\n%s\n' \
'{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18"}}' \
'{"jsonrpc":"2.0","id":2,"method":"tools/list"}' \
'{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"codemap","arguments":{"budget":2000}}}' \
| "$CG" mcp > "$TMP/mcp.out"
python3 - "$TMP/mcp.out" <<'EOF'
import json, sys
by_id = {l["id"]: l for l in map(json.loads, open(sys.argv[1])) if "id" in l}
tools = {t["name"]: t for t in by_id[2]["result"]["tools"]}
assert "codemap" in tools, sorted(tools)
assert tools["codemap"]["annotations"]["readOnlyHint"] is True
res = by_id[3]["result"]
assert not res.get("isError"), res
text = res["content"][0]["text"]
assert text.startswith("<!-- codify-owned: codemap v1 budget=2000"), text[:120]
assert "## Modules" in text and "text_words" in text, text
EOF
[ ! -e CODEMAP.md ] || fail "the MCP tool wrote CODEMAP.md"

echo "ok 38_codemap"
