/*
 * Agent context file generation: AGENTS.md / CLAUDE.md built from the graph —
 * languages, directory map, build tooling, entry points, routes, and the
 * most-referenced ("load-bearing") symbols, plus a cg cheatsheet so agents
 * can query the graph themselves.
 */
#include "cg.h"
#include <sys/stat.h>
#include <time.h>

typedef struct { char name[128]; int files; long lines;
                 char top_lang[32]; int top_lang_n;
                 char langs[8][32]; int langn[8]; int nlangs; } DirAgg;

static void dir_lang(DirAgg *d, const char *lang) {
    for (int i = 0; i < d->nlangs; i++)
        if (strcmp(d->langs[i], lang) == 0) {
            if (++d->langn[i] > d->top_lang_n) {
                d->top_lang_n = d->langn[i];
                snprintf(d->top_lang, sizeof d->top_lang, "%s", lang);
            }
            return;
        }
    if (d->nlangs < 8) {
        snprintf(d->langs[d->nlangs], 32, "%s", lang);
        d->langn[d->nlangs] = 1;
        if (d->top_lang_n == 0) {
            snprintf(d->top_lang, sizeof d->top_lang, "%s", lang);
            d->top_lang_n = 1;
        }
        d->nlangs++;
    }
}

static const struct { const char *file, *what; } TOOLING[] = {
    { "Makefile",           "make" },
    { "CMakeLists.txt",     "CMake" },
    { "package.json",       "npm/node" },
    { "go.mod",             "Go modules" },
    { "Cargo.toml",         "Cargo (Rust)" },
    { "pyproject.toml",     "Python (pyproject)" },
    { "requirements.txt",   "Python (pip)" },
    { "pom.xml",            "Maven (Java)" },
    { "build.gradle",       "Gradle" },
    { "build.gradle.kts",   "Gradle (Kotlin)" },
    { "composer.json",      "Composer (PHP)" },
    { "Gemfile",            "Bundler (Ruby)" },
    { "Dockerfile",         "Docker" },
    { "docker-compose.yml", "Docker Compose" },
    { "foundry.toml",       "Foundry (Solidity)" },
    { "hardhat.config.js",  "Hardhat (Solidity)" },
    { NULL, NULL }
};

int cmd_agentmd(Cg *cg, bool write_files) {
    StrBuf md; sb_init(&md);
    const char *base = strrchr(cg->root, '/');
    base = base && base[1] ? base + 1 : cg->root;

    char today[32] = "";
    time_t now = time(NULL);
    struct tm tmv;
    if (localtime_r(&now, &tmv)) strftime(today, sizeof today, "%Y-%m-%d", &tmv);

    sb_printf(&md, "# %s — Agent Context\n\n", base);
    sb_printf(&md, "_Generated by Codify " CG_VERSION " on %s. Regenerate "
                   "with `cg agentmd --write` after significant changes._\n\n",
              today);

    /* ---- language table ---- */
    sb_puts(&md, "## Languages\n\n| Language | Files | Lines |\n|---|---:|---:|\n");
    sqlite3_stmt *st = cg_prep(cg,
        "SELECT lang, COUNT(*), SUM(lines) FROM files WHERE lang IS NOT NULL "
        "GROUP BY lang ORDER BY 2 DESC");
    long tot_files = 0, tot_lines = 0;
    while (sqlite3_step(st) == SQLITE_ROW) {
        const char *lang = (const char *)sqlite3_column_text(st, 0);
        long nf = sqlite3_column_int64(st, 1);
        long nl = sqlite3_column_int64(st, 2);
        sb_printf(&md, "| %s | %ld | %ld |\n", lang, nf, nl);
        tot_files += nf;
        tot_lines += nl;
    }
    sqlite3_finalize(st);
    sb_printf(&md, "\n%ld source files, %ld lines total.\n\n",
              tot_files, tot_lines);

    /* ---- directory map ---- */
    sb_puts(&md, "## Directory map\n\n");
    DirAgg *dirs = xmalloc(sizeof(DirAgg) * 256);
    int ndirs = 0;
    st = cg_prep(cg, "SELECT path, lang, lines FROM files WHERE lang IS NOT NULL");
    while (sqlite3_step(st) == SQLITE_ROW) {
        const char *path = (const char *)sqlite3_column_text(st, 0);
        const char *lang = (const char *)sqlite3_column_text(st, 1);
        long lines = sqlite3_column_int64(st, 2);
        char seg[128];
        const char *slash = strchr(path, '/');
        if (slash) snprintf(seg, sizeof seg, "%.*s/", (int)(slash - path), path);
        else       snprintf(seg, sizeof seg, "(root)");
        DirAgg *d = NULL;
        for (int i = 0; i < ndirs; i++)
            if (strcmp(dirs[i].name, seg) == 0) { d = &dirs[i]; break; }
        if (!d && ndirs < 256) {
            d = &dirs[ndirs++];
            memset(d, 0, sizeof *d);
            snprintf(d->name, sizeof d->name, "%s", seg);
        }
        if (d) {
            d->files++;
            d->lines += lines;
            dir_lang(d, lang);
        }
    }
    sqlite3_finalize(st);
    for (int i = 0; i < ndirs; i++)
        sb_printf(&md, "- `%s` — %d files, %ld lines (mostly %s)\n",
                  dirs[i].name, dirs[i].files, dirs[i].lines, dirs[i].top_lang);
    free(dirs);
    sb_putc(&md, '\n');

    /* ---- build & tooling ---- */
    sb_puts(&md, "## Build & tooling\n\n");
    bool any_tool = false;
    for (int i = 0; TOOLING[i].file; i++) {
        char p[4900];
        snprintf(p, sizeof p, "%s/%s", cg->root, TOOLING[i].file);
        struct stat sb2;
        if (stat(p, &sb2) != 0) continue;
        any_tool = true;
        sb_printf(&md, "- `%s` — %s", TOOLING[i].file, TOOLING[i].what);
        if (strcmp(TOOLING[i].file, "package.json") == 0) {
            char *body = read_entire_file(p, NULL);
            char *scripts = body ? json_get_object(body, "scripts") : NULL;
            if (scripts) {
                char *keys[24];
                int nk = json_object_keys(scripts, keys, 24);
                if (nk) {
                    sb_puts(&md, " (scripts:");
                    for (int k = 0; k < nk; k++) {
                        sb_printf(&md, " `%s`", keys[k]);
                        free(keys[k]);
                    }
                    sb_putc(&md, ')');
                }
                free(scripts);
            }
            free(body);
        }
        sb_putc(&md, '\n');
    }
    if (!any_tool) sb_puts(&md, "- no standard build files detected\n");
    sb_putc(&md, '\n');

    /* ---- entry points ---- */
    sb_puts(&md, "## Entry points\n\n");
    int ne = 0;
    st = cg_prep(cg,
        "SELECT s.name, s.kind, f.path, s.line FROM symbols s "
        "JOIN files f ON f.id=s.file_id "
        "WHERE s.name IN ('main','Main','__main__') ORDER BY f.path LIMIT 15");
    while (sqlite3_step(st) == SQLITE_ROW) {
        sb_printf(&md, "- %s `%s` — `%s:%d`\n",
                  (const char *)sqlite3_column_text(st, 1),
                  (const char *)sqlite3_column_text(st, 0),
                  (const char *)sqlite3_column_text(st, 2),
                  sqlite3_column_int(st, 3));
        ne++;
    }
    sqlite3_finalize(st);
    if (!ne) sb_puts(&md, "- no `main` entry points (library or web project)\n");
    sb_putc(&md, '\n');

    /* ---- routes ---- */
    st = cg_prep(cg,
        "SELECT r.method, r.pattern, r.handler, f.path, r.line, r.framework "
        "FROM routes r JOIN files f ON f.id=r.file_id ORDER BY r.pattern LIMIT 60");
    int nr = 0;
    StrBuf rt; sb_init(&rt);
    while (sqlite3_step(st) == SQLITE_ROW) {
        const char *h = (const char *)sqlite3_column_text(st, 2);
        sb_printf(&rt, "| %s | `%s` | %s%s%s | `%s:%d` |\n",
                  (const char *)sqlite3_column_text(st, 0),
                  (const char *)sqlite3_column_text(st, 1),
                  h ? "`" : "", h ? h : "—", h ? "`" : "",
                  (const char *)sqlite3_column_text(st, 3),
                  sqlite3_column_int(st, 4));
        nr++;
    }
    sqlite3_finalize(st);
    if (nr) {
        sb_puts(&md, "## HTTP routes\n\n| Method | Pattern | Handler | Where |\n"
                     "|---|---|---|---|\n");
        sb_puts(&md, rt.p);
        sb_putc(&md, '\n');
    }
    sb_free(&rt);

    /* ---- load-bearing symbols ---- */
    sb_puts(&md, "## Load-bearing symbols (most referenced)\n\n");
    st = cg_prep(cg,
        "SELECT r.name, COUNT(*) AS c FROM refs r "
        "WHERE EXISTS(SELECT 1 FROM symbols s WHERE s.name=r.name) "
        "GROUP BY r.name ORDER BY c DESC LIMIT 15");
    sqlite3_stmt *loc = cg_prep(cg,
        "SELECT s.kind, f.path, s.line FROM symbols s "
        "JOIN files f ON f.id=s.file_id WHERE s.name=? ORDER BY s.id LIMIT 1");
    while (sqlite3_step(st) == SQLITE_ROW) {
        const char *name = (const char *)sqlite3_column_text(st, 0);
        int c = sqlite3_column_int(st, 1);
        sqlite3_bind_text(loc, 1, name, -1, SQLITE_TRANSIENT);
        if (sqlite3_step(loc) == SQLITE_ROW)
            sb_printf(&md, "- `%s` (%s, %d refs) — `%s:%d`\n", name,
                      (const char *)sqlite3_column_text(loc, 0), c,
                      (const char *)sqlite3_column_text(loc, 1),
                      sqlite3_column_int(loc, 2));
        sqlite3_reset(loc);
        sqlite3_clear_bindings(loc);
    }
    sqlite3_finalize(loc);
    sqlite3_finalize(st);

    /* ---- cheatsheet ---- */
    sb_puts(&md,
        "\n## Querying this codebase\n\n"
        "This project is indexed by Codify (SQLite + FTS5, 100% local). "
        "Prefer these over grep/file-walking — one call returns definitions, "
        "snippets, and call edges:\n\n"
        "```bash\n"
        "cg context <query>      # symbols + snippets + callers/callees + routes\n"
        "cg search <text>        # instant name/full-text search\n"
        "cg symbol <name>        # definition + snippet + reference count\n"
        "cg impact <name> -d 3   # who breaks if this changes\n"
        "cg routes [filter]      # URL pattern -> handler\n"
        "cg changes              # impact radius of uncommitted edits\n"
        "```\n\n"
        "All of the above accept `--json`. The graph auto-syncs via "
        "`cg watch`, or connect over MCP with `cg mcp-install`.\n");

    if (write_files) {
        const char *names[2] = { "AGENTS.md", "CLAUDE.md" };
        for (int i = 0; i < 2; i++) {
            char p[4900];
            snprintf(p, sizeof p, "%s/%s", cg->root, names[i]);
            if (write_entire_file(p, md.p, md.len) == 0)
                printf("wrote %s\n", p);
            else
                fprintf(stderr, "cg: cannot write %s\n", p);
        }
    } else {
        fputs(md.p, stdout);
    }
    sb_free(&md);
    return 0;
}
