/*
 * cg skills — the memories worth carrying, rendered as Agent Skills.
 *
 * `cg memory classify` asks Jev which memories are skills; this is what
 * happens to the ones that are. `cg skills promote <id>` writes
 * .agents/skills/<slug>/SKILL.md — the portable, vendor-neutral format every
 * agent host reads — from one memory, and `cg skills render` refreshes every
 * file already written so the generated copy never drifts from the note.
 *
 * Two rules keep this honest. The file is generated: it carries Codify's
 * ownership marker (the same "codify-owned:" convention integrate.c uses for
 * every asset it writes) naming the memory it came from, and a file without
 * that marker is never overwritten. And promotion lives in the file, not in
 * the database: `class` stays Jev's opinion of the memory, so re-classifying
 * never silently un-promotes a skill somebody is using.
 */
#include "cg.h"
#include <ctype.h>
#include <dirent.h>
#include <sys/stat.h>
#include <time.h>

#define SKILL_DIR    ".agents/skills"
#define SKILL_MARKER "codify-owned: memory-skill v1"
#define SKILL_SLUG_MAX 48

/* .agents/skills/<slug>/SKILL.md, plus room for a "-<id>" disambiguator */
typedef struct { char rel[320]; char slug[80]; long id; } SkillFile;

/* first line of the body, trimmed and capped — the human name of the skill */
static void skill_title(const Memory *m, char *out, size_t cap) {
    const char *p = m->body;
    while (*p == ' ' || *p == '\t') p++;
    size_t n = strcspn(p, "\n");
    if (n > cap - 1) {
        n = cap - 1;
        while (n && ((unsigned char)p[n] & 0xC0) == 0x80) n--;
    }
    while (n && (p[n - 1] == ' ' || p[n - 1] == '.')) n--;
    memcpy(out, p, n);
    out[n] = 0;
    if (!n) snprintf(out, cap, "Memory #%ld", m->id);
}

/* directory name: the title reduced to lowercase words joined by dashes */
static void skill_slug(const Memory *m, char *out, size_t cap) {
    size_t n = 0, max = cap - 1 < SKILL_SLUG_MAX ? cap - 1 : SKILL_SLUG_MAX;
    bool dash = false, cut = false;
    const char *p = m->body;
    for (; *p && *p != '\n'; p++) {
        unsigned char c = (unsigned char)*p;
        if (n >= max) { cut = isalnum(c) != 0; break; }
        if (isalnum(c)) { out[n++] = (char)tolower(c); dash = false; }
        else if (n && !dash) { out[n++] = '-'; dash = true; }
    }
    /* a directory named ...-before-w helps nobody: drop the half word */
    if (cut) while (n && out[n - 1] != '-') n--;
    while (n && out[n - 1] == '-') n--;
    out[n] = 0;
    if (!n) snprintf(out, cap, "memory-%ld", m->id);
}

/* YAML double-quoted scalar: the description is free text an agent wrote */
static void yaml_str(StrBuf *b, const char *s, size_t max) {
    sb_putc(b, '"');
    size_t n = 0;
    for (const char *p = s; *p && *p != '\n' && n < max; p++, n++) {
        if (*p == '"' || *p == '\\') sb_putc(b, '\\');
        sb_putc(b, *p);
    }
    sb_putc(b, '"');
}

/* The memory a generated file came from; -1 when the file is not ours. */
static long skill_memory_of(const char *body) {
    const char *p = strstr(body, SKILL_MARKER);
    if (!p) return -1;
    p = strstr(p, "memory #");
    return p ? atol(p + 8) : -1;
}

/* The whole SKILL.md, rendered from the memory alone, so the same memory
 * always produces the same bytes and `skills render` can tell drift from a
 * no-op. */
static char *skill_body(const Memory *m) {
    char title[200], slug[80];
    skill_title(m, title, sizeof title);
    skill_slug(m, slug, sizeof slug);
    char when[32] = "";
    time_t t = (time_t)m->created;
    struct tm tmv;
    if (localtime_r(&t, &tmv)) strftime(when, sizeof when, "%Y-%m-%d", &tmv);

    StrBuf b; sb_init(&b);
    sb_printf(&b, "---\nname: %s\ndescription: ", slug);
    yaml_str(&b, title, 160);
    sb_printf(&b, "\ngenerated_by: codify\nsource_memory: %ld\n---\n\n",
              m->id);
    sb_printf(&b, "<!-- %s — generated by Codify from memory #%ld. Edit the "
                  "memory and run `cg skills render`; edits made here are "
                  "overwritten. -->\n\n", SKILL_MARKER, m->id);
    sb_printf(&b, "# %s\n", title);
    /* The heading is the memory's first line. Printing the body verbatim
     * under it would repeat that line, so when the heading already says it,
     * only what follows is printed — and a one-line memory prints nothing. */
    const char *body = m->body;
    while (*body == ' ' || *body == '\t' || *body == '\n') body++;
    size_t first = strcspn(body, "\n");
    size_t head = first;
    while (head && (body[head - 1] == ' ' || body[head - 1] == '.')) head--;
    if (strlen(title) == head && strncmp(title, body, head) == 0)
        body += first;
    while (*body == '\n' || *body == ' ' || *body == '\t') body++;
    size_t blen = strlen(body);
    while (blen && (body[blen - 1] == ' ' || body[blen - 1] == '\n' ||
                    body[blen - 1] == '\t')) blen--;
    if (blen) sb_printf(&b, "\n%.*s\n", (int)blen, body);
    sb_puts(&b, "\n## Where this came from\n\n");
    sb_printf(&b, "- memory: #%ld — codify://memory/%ld\n", m->id, m->id);
    sb_printf(&b, "- kind: %s", m->type);
    if (m->cls) sb_printf(&b, ", classed %s (%.2f)", m->cls, m->confidence);
    if (when[0]) sb_printf(&b, ", recorded %s", when);
    sb_puts(&b, "\n");
    if (m->task) sb_printf(&b, "- task: %s\n", m->task);
    if (m->symbols) sb_printf(&b, "- symbols: %s\n", m->symbols);
    if (m->files) sb_printf(&b, "- files: %s\n", m->files);
    /* the note itself, back in the tool that owns it */
    sb_puts(&b, "- recall: `cg recall \"");
    int words = 0;
    for (const char *p = title; *p && words < 6; ) {
        size_t w = strcspn(p, " ");
        sb_printf(&b, "%s%.*s", words ? " " : "", (int)w, p);
        words++;
        p += w;
        while (*p == ' ') p++;
    }
    sb_puts(&b, "\"`\n");
    return b.p;
}

int skill_render(Cg *cg, const Memory *m, char *path_out, size_t cap) {
    char slug[80];
    skill_slug(m, slug, sizeof slug);
    char rel[320], abs[4700];
    snprintf(rel, sizeof rel, "%s/%s/SKILL.md", SKILL_DIR, slug);
    snprintf(abs, sizeof abs, "%s/%s", cg->root, rel);
    char *old = read_entire_file(abs, NULL);
    if (old && skill_memory_of(old) != m->id) {
        /* the slug is taken. By a file that is not ours: refuse. By another
         * memory's skill: two notes that start with the same words, so this
         * one keeps its id. */
        long owner = skill_memory_of(old);
        free(old);
        old = NULL;
        if (owner < 0) { snprintf(path_out, cap, "%s", rel); return 2; }
        snprintf(rel, sizeof rel, "%s/%s-%ld/SKILL.md", SKILL_DIR, slug, m->id);
        snprintf(abs, sizeof abs, "%s/%s", cg->root, rel);
        old = read_entire_file(abs, NULL);
        if (old && skill_memory_of(old) != m->id) {
            free(old);
            snprintf(path_out, cap, "%s", rel);
            return 2;
        }
    }
    snprintf(path_out, cap, "%s", rel);
    char *body = skill_body(m);
    if (old && strcmp(old, body) == 0) { free(old); free(body); return 1; }
    free(old);
    char dir[4700];
    snprintf(dir, sizeof dir, "%s", abs);
    char *cut = strrchr(dir, '/');
    if (cut) *cut = 0;
    int rc = 0;
    if (mkdirs(dir) != 0 || write_entire_file(abs, body, strlen(body)) != 0)
        rc = -1;
    free(body);
    return rc;
}

/* Every SKILL.md under .agents/skills that Codify generated. Somebody
 * else's skill (no marker) is not our business and is left alone. */
static int skill_scan(Cg *cg, SkillFile **out) {
    *out = NULL;
    char base[4700];
    snprintf(base, sizeof base, "%s/%s", cg->root, SKILL_DIR);
    DIR *d = opendir(base);
    if (!d) return 0;
    int n = 0, cap = 8;
    SkillFile *v = xmalloc(sizeof(SkillFile) * (size_t)cap);
    struct dirent *e;
    while ((e = readdir(d))) {
        size_t nlen = strlen(e->d_name);
        /* a directory Codify wrote is named by a slug; anything longer than
         * one can be is somebody else's */
        if (e->d_name[0] == '.' || nlen >= sizeof v[0].slug) continue;
        char file[5000];
        snprintf(file, sizeof file, "%s/%s/SKILL.md", base, e->d_name);
        char *body = read_entire_file(file, NULL);
        if (!body) continue;
        long id = skill_memory_of(body);
        free(body);
        if (id < 0) continue;
        if (n == cap) { cap *= 2; v = xrealloc(v, sizeof(SkillFile) * (size_t)cap); }
        memcpy(v[n].slug, e->d_name, nlen + 1);
        snprintf(v[n].rel, sizeof v[n].rel, "%s/%s/SKILL.md", SKILL_DIR,
                 v[n].slug);
        v[n].id = id;
        n++;
    }
    closedir(d);
    /* readdir order is the filesystem's; a report should not shuffle */
    for (int i = 1; i < n; i++)
        for (int j = i; j > 0 && strcmp(v[j - 1].slug, v[j].slug) > 0; j--) {
            SkillFile t = v[j - 1]; v[j - 1] = v[j]; v[j] = t;
        }
    *out = v;
    return n;
}

/* true when the generated file still matches what the memory renders to */
static bool skill_current(Cg *cg, const SkillFile *f, const Memory *m) {
    char abs[4700];
    snprintf(abs, sizeof abs, "%s/%s", cg->root, f->rel);
    char *have = read_entire_file(abs, NULL);
    if (!have) return false;
    char *want = skill_body(m);
    bool same = strcmp(have, want) == 0;
    free(have); free(want);
    return same;
}

int skill_findings(Cg *cg, char ***out) {
    *out = NULL;
    SkillFile *v = NULL;
    int nf = skill_scan(cg, &v);
    if (nf == 0) { free(v); return 0; }
    char **lines = xmalloc(sizeof(char *) * (size_t)nf);
    int n = 0;
    for (int i = 0; i < nf; i++) {
        Memory m;
        StrBuf b; sb_init(&b);
        if (!memory_get(cg, v[i].id, &m)) {
            sb_printf(&b, "generated skill %s came from memory #%ld, which no "
                          "longer exists", v[i].rel, v[i].id);
            lines[n++] = b.p;
            continue;
        }
        if (!skill_current(cg, &v[i], &m))
            sb_printf(&b, "generated skill %s is out of date with memory "
                          "#%ld — run cg skills render", v[i].rel, v[i].id);
        if (b.len) lines[n++] = b.p;
        else sb_free(&b);
        memory_clear(&m);
    }
    free(v);
    if (!n) { free(lines); return 0; }
    *out = lines;
    return n;
}

/* ---------------- the command ---------------- */

/* Memories Jev called skills, newest confidence first — the shortlist a
 * human picks from. */
static int skill_candidates(Cg *cg, Memory **out) {
    /* ids first, rows through memory_get: one place reads a memory row */
    sqlite3_stmt *st = cg_prep(cg,
        "SELECT id FROM memories WHERE class='skill' "
        "ORDER BY ifnull(confidence,0) DESC, id");
    int n = 0, cap = 8;
    Memory *v = xmalloc(sizeof(Memory) * (size_t)cap);
    while (sqlite3_step(st) == SQLITE_ROW) {
        long id = (long)sqlite3_column_int64(st, 0);
        if (n == cap) { cap *= 2; v = xrealloc(v, sizeof(Memory) * (size_t)cap); }
        if (memory_get(cg, id, &v[n])) n++;
    }
    sqlite3_finalize(st);
    *out = v;
    return n;
}

static const char *skill_path_for(const SkillFile *v, int n, long id) {
    for (int i = 0; i < n; i++) if (v[i].id == id) return v[i].rel;
    return NULL;
}

static void skill_row_json(StrBuf *b, const Memory *m, const char *path,
                           bool stale) {
    char slug[80], title[200];
    skill_slug(m, slug, sizeof slug);
    skill_title(m, title, sizeof title);
    sb_printf(b, "{\"id\":%ld,\"slug\":", m->id);
    sb_json_str(b, slug);
    sb_puts(b, ",\"title\":");
    sb_json_str(b, title);
    sb_puts(b, ",\"class\":");
    if (m->cls) sb_json_str(b, m->cls); else sb_puts(b, "null");
    sb_printf(b, ",\"confidence\":%.2f,\"type\":", m->confidence);
    sb_json_str(b, m->type);
    sb_puts(b, ",\"task\":");
    if (m->task) sb_json_str(b, m->task); else sb_puts(b, "null");
    sb_printf(b, ",\"promoted\":%s,\"path\":", path ? "true" : "false");
    if (path) sb_json_str(b, path); else sb_puts(b, "null");
    sb_printf(b, ",\"stale\":%s}", stale ? "true" : "false");
}

static int skills_list(Cg *cg, bool json) {
    Memory *cand = NULL;
    int nc = skill_candidates(cg, &cand);
    SkillFile *files = NULL;
    int nf = skill_scan(cg, &files);

    StrBuf b; sb_init(&b);
    int rows = 0, promoted = 0;
    if (json) sb_puts(&b, "{\"skills\":[");
    for (int i = 0; i < nc; i++) {
        const char *path = skill_path_for(files, nf, cand[i].id);
        bool stale = false;
        for (int j = 0; path && j < nf; j++)
            if (files[j].id == cand[i].id)
                stale = !skill_current(cg, &files[j], &cand[i]);
        if (path) promoted++;
        if (json) {
            if (rows) sb_putc(&b, ',');
            skill_row_json(&b, &cand[i], path, stale);
        } else {
            char title[200];
            skill_title(&cand[i], title, sizeof title);
            sb_printf(&b, "  #%-4ld %-9s %.2f  %s\n", cand[i].id,
                      path ? (stale ? "stale" : "promoted") : "candidate",
                      cand[i].confidence, title);
            if (path) sb_printf(&b, "        %s\n", path);
            else sb_printf(&b, "        cg skills promote %ld\n", cand[i].id);
        }
        rows++;
    }
    /* a skill promoted by hand, or re-classified since, is still a skill:
     * the rendered file is the record of promotion */
    for (int i = 0; i < nf; i++) {
        bool listed = false;
        for (int j = 0; j < nc; j++) if (cand[j].id == files[i].id) listed = true;
        if (listed) continue;
        Memory m;
        if (!memory_get(cg, files[i].id, &m)) continue;
        bool stale = !skill_current(cg, &files[i], &m);
        promoted++;
        if (json) {
            if (rows) sb_putc(&b, ',');
            skill_row_json(&b, &m, files[i].rel, stale);
        } else {
            char title[200];
            skill_title(&m, title, sizeof title);
            sb_printf(&b, "  #%-4ld %-9s %.2f  %s\n        %s\n", m.id,
                      stale ? "stale" : "promoted", m.confidence, title,
                      files[i].rel);
        }
        rows++;
        memory_clear(&m);
    }
    if (json) {
        sb_printf(&b, "],\"count\":%d,\"promoted\":%d,\"dir\":\"%s\"}\n",
                  rows, promoted, SKILL_DIR);
        fputs(b.p, stdout);
    } else if (!rows) {
        printf("no skills yet — run `cg memory classify --all` to find "
               "candidates\n");
    } else {
        printf("skills — %d candidate(s), %d promoted under %s:\n", rows,
               promoted, SKILL_DIR);
        fputs(b.p, stdout);
    }
    sb_free(&b);
    memory_free(cand, nc);
    free(files);
    return 0;
}

static int skills_promote(Cg *cg, const char *idstr, bool json) {
    if (idstr && idstr[0] == '#') idstr++;
    long id = idstr ? atol(idstr) : 0;
    if (id <= 0) {
        fprintf(stderr, "usage: cg skills promote <memory-id>\n");
        return 1;
    }
    Memory m;
    if (!memory_get(cg, id, &m)) {
        fprintf(stderr, "cg: no memory #%ld\n", id);
        return 1;
    }
    char path[320];
    int rc = skill_render(cg, &m, path, sizeof path);
    if (rc == 2) {
        fprintf(stderr, "cg: %s already exists and was not generated by "
                "Codify — move it aside first\n", path);
        memory_clear(&m);
        return 1;
    }
    if (rc < 0) {
        fprintf(stderr, "cg: could not write %s\n", path);
        memory_clear(&m);
        return 1;
    }
    /* Jev's verdict is not a veto — a human may promote anything — but a
     * promotion it disagrees with is worth saying out loud */
    if (m.cls && strcmp(m.cls, "skill") != 0)
        fprintf(stderr, "cg: note — memory #%ld is classed %s (%.2f)\n", id,
                m.cls, m.confidence);
    char slug[80];
    skill_slug(&m, slug, sizeof slug);
    if (json) {
        StrBuf b; sb_init(&b);
        sb_printf(&b, "{\"ok\":true,\"id\":%ld,\"slug\":", id);
        sb_json_str(&b, slug);
        sb_puts(&b, ",\"path\":");
        sb_json_str(&b, path);
        sb_printf(&b, ",\"written\":%s,\"class\":", rc == 0 ? "true" : "false");
        if (m.cls) sb_json_str(&b, m.cls); else sb_puts(&b, "null");
        sb_printf(&b, ",\"confidence\":%.2f}\n", m.confidence);
        fputs(b.p, stdout);
        sb_free(&b);
    } else {
        printf("promoted #%ld -> %s%s\n", id, path,
               rc == 1 ? " (already up to date)" : "");
    }
    memory_clear(&m);
    return 0;
}

static int skills_render_all(Cg *cg, bool json) {
    SkillFile *files = NULL;
    int nf = skill_scan(cg, &files);
    StrBuf done; sb_init(&done);
    StrBuf orphan; sb_init(&orphan);
    int nd = 0, no = 0, changed = 0;
    for (int i = 0; i < nf; i++) {
        Memory m;
        if (!memory_get(cg, files[i].id, &m)) {
            if (json) {
                if (no) sb_putc(&orphan, ',');
                sb_printf(&orphan, "{\"id\":%ld,\"path\":", files[i].id);
                sb_json_str(&orphan, files[i].rel);
                sb_putc(&orphan, '}');
            } else {
                sb_printf(&orphan, "  %s — memory #%ld no longer exists\n",
                          files[i].rel, files[i].id);
            }
            no++;
            continue;
        }
        char path[320];
        int rc = skill_render(cg, &m, path, sizeof path);
        const char *state = rc == 0 ? "updated" : rc == 1 ? "unchanged" :
                            rc == 2 ? "conflict" : "failed";
        if (rc == 0) changed++;
        if (json) {
            if (nd) sb_putc(&done, ',');
            sb_printf(&done, "{\"id\":%ld,\"path\":", m.id);
            sb_json_str(&done, path);
            sb_printf(&done, ",\"status\":\"%s\"}", state);
        } else {
            sb_printf(&done, "  %-9s  %s (memory #%ld)\n", state, path, m.id);
        }
        nd++;
        memory_clear(&m);
    }
    free(files);
    if (json) {
        printf("{\"rendered\":[%s],\"orphans\":[%s],\"count\":%d,"
               "\"updated\":%d}\n", done.p, orphan.p, nd, changed);
    } else if (!nd && !no) {
        printf("no generated skills yet — promote a candidate with "
               "`cg skills promote <id>`\n");
    } else {
        if (nd) {
            printf("rendered %d skill(s), %d updated:\n", nd, changed);
            fputs(done.p, stdout);
        }
        if (no) {
            printf("orphaned:\n");
            fputs(orphan.p, stdout);
        }
    }
    sb_free(&done);
    sb_free(&orphan);
    return 0;
}

int cmd_skills(Cg *cg, int argc, char **argv, bool json) {
    const char *sub = argc >= 3 ? argv[2] : "list";
    if (strcmp(sub, "list") == 0) return skills_list(cg, json);
    if (strcmp(sub, "promote") == 0)
        return skills_promote(cg, argc >= 4 ? argv[3] : NULL, json);
    if (strcmp(sub, "render") == 0) return skills_render_all(cg, json);
    fprintf(stderr,
            "usage: cg skills list | promote <memory-id> | render\n");
    return 1;
}
